
private void ApplicationEvents_OnNewEditObject(object EditObject,
                                               EventTimingEnum BeforeOrAfter,
                                               NameValueMap Context,
                                               out HandlingCodeEnum HandlingCode)
{
    HandlingCode = HandlingCodeEnum.kEventNotHandled;

    if (BeforeOrAfter == EventTimingEnum.kAfter)
    {
        if (EditObject is PartDocument) {
            object obj = m_Application.ActiveEditDocument.ActivatedObject;

            // ここで、objは常にnullのはずだが、3Dスケッチから抜けたときだけは、nullではない。
            // フィーチャーもしくはスケッチが編集中かどうかを、
            // ActiveEditDocument.ActivatedObject == nullで判断すると、バグる。
            // 代わりに、EditObjectがDocumentかどうかで判断することで、回避する。
        }
    }
}

