using Inventor;
using System;

namespace InventorAccessor
{
    class Program
    {
        static void Main(string[] args)
        {
            var invApp = (Application)System.Runtime.InteropServices.Marshal.GetActiveObject("Inventor.Application");
            Console.WriteLine($"Version {invApp.SoftwareVersion.DisplayName}");

            var document = invApp.ActiveEditDocument;
            if (document is null)
            {
                Console.WriteLine($"document is null.");
            }
            else
            {
                Console.WriteLine($"SelectSet.Count : {document.SelectSet.Count}");
            }

            Console.WriteLine("Hit any key.");
            _ = Console.ReadKey();
        }
    }
}

