/// &lt;summary&gt;
/// 要素IDコレクションを取得する
/// &lt;param name="revit"&gt;ExternalCommandData&lt;/param&gt;
/// &lt;return&gt;要素IDコレクション&lt;/return&gt;
/// &lt;/summary&gt;
private ICollection&lt;ElementId&gt; GetElementIds(ExternalCommandData revit)
{
    UIApplication uiapp = revit.Application;
    UIDocument uidoc = uiapp.ActiveUIDocument;
    Application app = uiapp.Application;
    Document doc = uidoc.Document;

    // フィルターセット(例では解析モデル床でフィルタリング)
    ElementCategoryFilter filter = new ElementCategoryFilter(BuiltInCategory.OST_FloorAnalytical);
    FilteredElementCollector collector = new FilteredElementCollector(doc);
    elementIds = collector.WherePasses(filter).WhereElementIsNotElementType().ToElementIds();

    // 要素IDを取得する
    return elementIds;
}

